import type { MappingAuditRecord, MappingRegistryVersion, MappingVersionDiff } from "./types";

export function MappingVersions({ versions, audits, selected, diff, onSelect, onRollback, canRollback }: { versions: MappingRegistryVersion[]; audits: MappingAuditRecord[]; selected?: MappingRegistryVersion; diff?: MappingVersionDiff; onSelect: (version: number) => void; onRollback: (version: number) => void; canRollback: boolean }) {
  return <div className="versions-layout"><aside className="version-list"><h3>Mapping Versions</h3>{versions.map((version) => <button key={version.id} className={selected?.version === version.version ? "active" : ""} onClick={() => onSelect(version.version)}><span><strong>v{version.version}</strong><em className={version.status}>{version.status}</em></span><small>{formatDate(version.updatedAt)} · {version.publishedBy || version.createdBy || "system"}</small></button>)}</aside><section className="version-detail">{selected ? <><header><div><h3>v{selected.version} · {selected.status}</h3><p>{selected.changeSummary || "未填写修改摘要"}</p></div>{canRollback && selected.status !== "draft" && <button onClick={() => onRollback(selected.version)}>回滚到此版本</button>}</header><div className="version-meta"><span>实体 <strong>{selected.entities.length}</strong></span><span>Join <strong>{selected.joinPaths.length}</strong></span><span>Validation <strong>{selected.validation.valid ? "Passed" : "Failed"}</strong></span></div>{diff && <MappingDiff diff={diff} />}<h4>Entity / Field Mapping</h4><div className="version-mapping-list">{selected.entities.map((entity) => <div key={entity.entity}><strong>{entity.entity} → {entity.table}</strong>{Object.entries(entity.fields).map(([field, column]) => <code key={field}>{field} → {column}</code>)}</div>)}</div><h4>Join Paths</h4><div className="version-join-list">{selected.joinPaths.map((join) => <p key={join.id}><strong>{join.leftEntity} → {join.rightEntity}</strong><span>{join.fields.map((pair) => `${pair.leftField} = ${pair.rightField}`).join(" + ")}</span></p>)}{!selected.joinPaths.length && <p>此版本未配置 Join Path。</p>}</div>{!selected.validation.valid && <div className="version-validation-errors">{selected.validation.errors.map((error) => <p key={error}>✕ {error}</p>)}</div>}<h4>审计记录</h4><div className="audit-list">{audits.filter((item) => item.version === selected.version).map((item) => <p key={item.id}><span>{item.action}</span><strong>{item.userId}</strong><time>{formatDate(item.timestamp)}</time></p>)}</div></> : <div className="semantic-empty"><h3>选择一个版本</h3><p>查看 Mapping、Join、Validation、Diff 与审计信息。</p></div>}</section></div>;
}

function MappingDiff({ diff }: { diff: MappingVersionDiff }) {
  const empty = !diff.addedMappings.length && !diff.changedMappings.length && !diff.removedMappings.length && !diff.addedJoins.length && !diff.removedJoins.length;
  return <div className="mapping-diff"><h4>相对上一发布版本</h4>{empty && <p>无结构化差异</p>}{diff.addedMappings.map((item) => <code className="added" key={`a-${item}`}>+ {item}</code>)}{diff.changedMappings.map((item) => <div key={item.field}><code className="removed">- {item.field} → {item.before}</code><code className="added">+ {item.field} → {item.after}</code></div>)}{diff.removedMappings.map((item) => <code className="removed" key={`r-${item}`}>- {item}</code>)}{diff.addedJoins.map((item) => <code className="added" key={`aj-${item}`}>+ {item}</code>)}{diff.removedJoins.map((item) => <code className="removed" key={`rj-${item}`}>- {item}</code>)}</div>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
